services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

  rinha-db:
    image: postgres:latest
    container_name: rinha-db
    #    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - rinha-db:/data/postgres
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=2096 -c synchronous_commit=0 -c full_page_writes=0 -c fsync=off -c check_function_bodies=false
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "115MB"

  api01: &api
    image: gianimpronta/rdb-2024-q1-spring-boot:jvm
    hostname: api01
    #    environment:
    #      - DB_HOSTNAME=db
    ports:
      - "8081:8080"
    depends_on:
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "210MB"

  api02:
    <<: *api
    hostname: api02
    #    environment:
    #      - DB_HOSTNAME=db
    ports:
      - "8082:8080"

#  pgAdmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - db

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

volumes:
  rinha-db: