version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"

  rinha-db:
    image: postgres:latest
    container_name: rinha-db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres.conf:/etc/postgres/postgres.conf
      - rinha-db:/data/postgres
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=2096 -c synchronous_commit=0 -c full_page_writes=0 -c fsync=off -c check_function_bodies=false
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  api01: &api
    image: gianimpronta/rdb-2024-q1-spring-boot:native
    hostname: api01
    ports:
      - "8081:8080"
    depends_on:
      rinha-db:
        condition:
          service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "210MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

networks:
  default:
    name: rinha-nginx-2024q1
    driver: bridge

volumes:
  rinha-db: