spring:
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/${POSTGRES_DB:rinha}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:123}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      accept-float-as-int: false